# Generated by Django 5.0.6 on 2024-07-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=15)),
                ('descricao', models.TextField(max_length=1000)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%y/%m/%d')),
            ],
        ),
    ]
