# Generated by Django 5.0.6 on 2024-07-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='descricao',
            field=models.TextField(max_length=2000),
        ),
    ]
