# Generated by Django 5.0.6 on 2024-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_fotos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='genero',
            field=models.CharField(blank=True, choices=[('LITERATURA BRASILEIRA', 'literatura brasileira'), ('MANGÁ', 'mangá'), ('FICÇAO CIENTÍFICA', 'ficçao científica'), ('TERROR', ' terror'), ('ROMANCE', 'romance'), ('POESIA', 'poesia')], max_length=50, null=True),
        ),
    ]
